---

- name: Ensure ssh configuration for ansible OS prepared - {{ bootstrap4ansible_user }}
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config
    block: |
      Match User {{ bootstrap4ansible_user }}
        PasswordAuthentication no
        AllowTcpForwarding yes
        X11Forwarding no
        PubkeyAuthentication yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK, ansible user - {{ bootstrap4ansible_user }}"
  notify:
    - Reload sshd service
