---

- name: Ensure sudoers config folder /etc/sudoers.d exists
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Ensure sudoers config file /etc/sudoers.d/ansible prepared for ansible user - {{ bootstrap4ansible_user }}
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0750'
    content: |
      # BEGIN ANSIBLE MANAGED BLOCK
      ansible ALL=(ALL:ALL) NOPASSWD: ALL
      # END ANSIBLE MANAGED BLOCK
    validate: visudo -cf %s
