---

- name: Converge
  hosts: all

- import_playbook: ../../tests/tests_default.yml
- import_playbook: ../../tests/tests_public_key_file.yml
- import_playbook: ../../tests/tests_generate_ssh_key.yml
